services:
  main-platform:
    build: .
    container_name: main-container-node
    stdin_open: true
    tty: true
    command: mvn exec:java -Dexec.mainClass="jade.Boot" -Dexec.args="-port 1099 Interfaz:com.sma.agents.AgenteInterfaz;Tokenizer:com.sma.agents.AgenteTokenizer;Clasificador:com.sma.agents.AgenteClasificador"
    ports:
      - "1099:1099"

  remote-platform:
    build: .
    container_name: remote-container-node
    depends_on:
      - main-platform
    # Usamos sh -c con las comillas correctas
    command: sh -c 'sleep 10 && mvn exec:java -Dexec.mainClass="jade.Boot" -Dexec.args="-container -host main-platform -port 1099 Repositorio:com.sma.agents.AgenteRepositorio"'
